spring.application.name=backend-server

# --- PostgreSQL Config ---
spring.datasource.url=jdbc:postgresql://localhost:5433/mhsa_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- Redis Config (Cho Auth Token) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password= (Bỏ trống nếu chạy local không pass)

# --- JWT Secret (Tự bịa một chuỗi thật dài và bí mật) ---
mhsa.app.jwtSecret=${JWT_SECRET}
mhsa.app.jwtExpirationMs=86400000 
# (24 giờ)

# --- Gemini AI Configuration ---
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent