spring.application.name=backend-server

# --- PostgreSQL Config ---
spring.datasource.url=jdbc:postgresql://localhost:5433/mhsa_db
spring.datasource.username=postgres
-spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Redis Config ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- JWT Secret ---
# Đặt trực tiếp chuỗi Base64 vào đây, bỏ hoàn toàn ${JWT_SECRET}
mhsa.app.jwtSecret=U2VjcmV0S2V5Q3VhTmhvbUJhblRhbUdpYW9UaGVzaXMyMDI2UGhhaURhaVZhRHVNYW5oRGVLaG9uZ0JpSGFjaw==
mhsa.app.jwtExpirationMs=86400000 

# --- Gemini AI Configuration ---
# Tạm thời đặt trực tiếp key ở đây để test app
gemini.api.key=AIzaSyCbHzuM4OFqTRfe6xtqFJIRRh01Z6lxP2E
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent