spring.application.name=backend-server

# --- PostgreSQL Config ---
spring.datasource.url=jdbc:postgresql://localhost:5433/mhsa_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- Redis Config (Cho Auth Token) ---
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password= (Bỏ trống nếu chạy local không pass)

# --- JWT Secret (Tự bịa một chuỗi thật dài và bí mật) ---
bantamgiao.app.jwtSecret=SecretKeyCuaNhomBanTamGiaoThesis2026PhaiDaiVaDuManhDeKhongBiHack
bantamgiao.app.jwtExpirationMs=86400000 
# (24 giờ)